services:
  
  db:
    image: postgres:latest
    container_name: accesspim-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: INDT_2026
      POSTGRES_DB: accesspim
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

# -----------------------------------------------------------------
# SEÇÃO DE DECLARAÇÃO DE VOLUMES (Onde o erro estava)
# -----------------------------------------------------------------
volumes:
  db_data: # O volume deve ser declarado aqui para ser reconhecido
    driver: local